// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TripCore.Infrastructure.Data;

#nullable disable

namespace TripCore.Infrastructure.Migrations
{
    [DbContext(typeof(TripCoreDbContext))]
    [Migration("20260328152644_AddIsIntensiveSupportAndCatalogueFlag")]
    partial class AddIsIntensiveSupportAndCatalogueFlag
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TripCore.Domain.Entities.AccommodationProperty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessibilityNotes")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<int?>("BedCount")
                        .HasColumnType("integer");

                    b.Property<string>("BeddingConfiguration")
                        .HasColumnType("text");

                    b.Property<int?>("BedroomCount")
                        .HasColumnType("integer");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("GeneralNotes")
                        .HasColumnType("text");

                    b.Property<string>("HoistBathroomNotes")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFullyModified")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSemiModified")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsWheelchairAccessible")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("MaxCapacity")
                        .HasColumnType("integer");

                    b.Property<string>("Mobile")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Postcode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProviderOwner")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("State")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Suburb")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Website")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsWheelchairAccessible");

                    b.HasIndex("Region");

                    b.HasIndex("TenantId");

                    b.ToTable("AccommodationProperties");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.AccommodationReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccommodationPropertyId")
                        .HasColumnType("uuid");

                    b.Property<int?>("BedroomsReserved")
                        .HasColumnType("integer");

                    b.Property<int?>("BedsReserved")
                        .HasColumnType("integer");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("text");

                    b.Property<DateOnly>("CheckInDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("CheckOutDate")
                        .HasColumnType("date");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<string>("ConfirmationReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("Cost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateOnly?>("DateBooked")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateConfirmed")
                        .HasColumnType("date");

                    b.Property<bool>("HasOverlapConflict")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("RequestSentDate")
                        .HasColumnType("date");

                    b.Property<int>("ReservationStatus")
                        .HasColumnType("integer");

                    b.Property<Guid>("TripInstanceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ReservationStatus");

                    b.HasIndex("TripInstanceId");

                    b.HasIndex("AccommodationPropertyId", "CheckInDate", "CheckOutDate");

                    b.ToTable("AccommodationReservations");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessibilityNotes")
                        .HasColumnType("text");

                    b.Property<string>("ActivityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("EventTemplateId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("SuitabilityNotes")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("EventTemplateId");

                    b.HasIndex("IsActive");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.AppSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("QualificationWarningDays")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.BookingTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AccommodationReservationId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("CompletedDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParticipantBookingId")
                        .HasColumnType("uuid");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<Guid?>("StaffAssignmentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TaskType")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("TripInstanceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("VehicleAssignmentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccommodationReservationId");

                    b.HasIndex("DueDate");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ParticipantBookingId");

                    b.HasIndex("Priority");

                    b.HasIndex("StaffAssignmentId");

                    b.HasIndex("Status");

                    b.HasIndex("TaskType");

                    b.HasIndex("TripInstanceId");

                    b.HasIndex("VehicleAssignmentId");

                    b.ToTable("BookingTasks");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.ClaimLineItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ClaimType")
                        .HasColumnType("integer");

                    b.Property<int>("DayType")
                        .HasColumnType("integer");

                    b.Property<int>("GSTCode")
                        .HasColumnType("integer");

                    b.Property<decimal>("Hours")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("PaidAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("ParticipantApproved")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ParticipantBookingId")
                        .HasColumnType("uuid");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SupportItemCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly>("SupportsDeliveredFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly>("SupportsDeliveredTo")
                        .HasColumnType("date");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("TripClaimId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantBookingId");

                    b.HasIndex("Status");

                    b.HasIndex("TripClaimId");

                    b.ToTable("ClaimLineItems");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<int>("ContactType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Mobile")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Organisation")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Postcode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("PreferredContactMethod")
                        .HasColumnType("integer");

                    b.Property<string>("RoleRelationship")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("State")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Suburb")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.EventTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessibilityNotes")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DefaultDestination")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DefaultRegion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EventCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FullyModifiedAccommodationNotes")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PreferredTimeOfYear")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SemiModifiedAccommodationNotes")
                        .HasColumnType("text");

                    b.Property<int?>("StandardDurationDays")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TypicalActivities")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("WheelchairAccessNotes")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EventCode")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.HasIndex("TenantId");

                    b.ToTable("EventTemplates");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.IncidentReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CorrectiveActions")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmergencyServicesDetails")
                        .HasColumnType("text");

                    b.Property<bool>("FamilyNotified")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("FamilyNotifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ImmediateActionsTaken")
                        .HasColumnType("text");

                    b.Property<DateTime>("IncidentDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IncidentType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("InvolvedParticipantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InvolvedStaffId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<Guid?>("ParticipantBookingId")
                        .HasColumnType("uuid");

                    b.Property<string>("QscReferenceNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("QscReportedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("QscReportingStatus")
                        .HasColumnType("integer");

                    b.Property<Guid>("ReportedByStaffId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ReviewNotes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ReviewedByStaffId")
                        .HasColumnType("uuid");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<bool>("SupportCoordinatorNotified")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("SupportCoordinatorNotifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("TripInstanceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("WereEmergencyServicesCalled")
                        .HasColumnType("boolean");

                    b.Property<string>("WitnessNames")
                        .HasColumnType("text");

                    b.Property<string>("WitnessStatements")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InvolvedParticipantId");

                    b.HasIndex("InvolvedStaffId");

                    b.HasIndex("IsActive");

                    b.HasIndex("ParticipantBookingId");

                    b.HasIndex("QscReportingStatus");

                    b.HasIndex("ReportedByStaffId");

                    b.HasIndex("ReviewedByStaffId");

                    b.HasIndex("Severity");

                    b.HasIndex("Status");

                    b.HasIndex("TripInstanceId");

                    b.ToTable("IncidentReports");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BehaviourRiskSummary")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("EquipmentRequirements")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FundingOrganisation")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("HasRestrictivePracticeFlag")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsHighSupport")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsIntensiveSupport")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRepeatClient")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MedicalSummary")
                        .HasColumnType("text");

                    b.Property<string>("MobilityNotes")
                        .HasColumnType("text");

                    b.Property<string>("NdisNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("PlanEndDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("PlanManagerContactId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("PlanStartDate")
                        .HasColumnType("date");

                    b.Property<int>("PlanType")
                        .HasColumnType("integer");

                    b.Property<string>("PreferredName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("RequiresOvernightSupport")
                        .HasColumnType("boolean");

                    b.Property<int>("SupportRatio")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TransportRequirements")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("WheelchairRequired")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("NdisNumber");

                    b.HasIndex("PlanManagerContactId");

                    b.HasIndex("Region");

                    b.HasIndex("SupportRatio");

                    b.HasIndex("TenantId");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.ParticipantBooking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("ActionRequired")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("BookingDate")
                        .HasColumnType("date");

                    b.Property<string>("BookingNotes")
                        .HasColumnType("text");

                    b.Property<int>("BookingStatus")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("CancellationNoticeDate")
                        .HasColumnType("date");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("text");

                    b.Property<int>("ClaimStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("EquipmentNotes")
                        .HasColumnType("text");

                    b.Property<string>("FundingNotes")
                        .HasColumnType("text");

                    b.Property<bool>("HasRestrictivePracticeFlag")
                        .HasColumnType("boolean");

                    b.Property<bool>("HighSupportRequired")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("InsuranceCoverageEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("InsuranceCoverageStart")
                        .HasColumnType("date");

                    b.Property<string>("InsurancePolicyNumber")
                        .HasColumnType("text");

                    b.Property<string>("InsuranceProvider")
                        .HasColumnType("text");

                    b.Property<int>("InsuranceStatus")
                        .HasColumnType("integer");

                    b.Property<bool>("NightSupportRequired")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("integer");

                    b.Property<int?>("PlanTypeOverride")
                        .HasColumnType("integer");

                    b.Property<string>("RiskSupportNotes")
                        .HasColumnType("text");

                    b.Property<string>("RoomPreference")
                        .HasColumnType("text");

                    b.Property<int?>("SupportRatioOverride")
                        .HasColumnType("integer");

                    b.Property<string>("TransportNotes")
                        .HasColumnType("text");

                    b.Property<Guid>("TripInstanceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("WheelchairRequired")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("BookingStatus");

                    b.HasIndex("InsuranceStatus");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("TripInstanceId", "ParticipantId")
                        .IsUnique();

                    b.ToTable("ParticipantBookings");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.ParticipantContact", b =>
                {
                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("uuid");

                    b.HasKey("ParticipantId", "ContactId");

                    b.HasIndex("ContactId");

                    b.ToTable("ParticipantContacts");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.ProviderSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ABN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("BSB")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("BankAccountName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("GSTRegistered")
                        .HasColumnType("boolean");

                    b.Property<string>("InvoiceFooterNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsPaceProvider")
                        .HasColumnType("boolean");

                    b.Property<string>("OrganisationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProviderSettings");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.PublicHoliday", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("State")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("Date", "State");

                    b.ToTable("PublicHolidays");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.ScheduledActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessibilityNotes")
                        .HasColumnType("text");

                    b.Property<Guid?>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<string>("BookingReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<decimal?>("EstimatedCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("ProviderEmail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProviderName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProviderPhone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ProviderWebsite")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TripDayId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("SortOrder");

                    b.HasIndex("Status");

                    b.HasIndex("TripDayId");

                    b.ToTable("ScheduledActivities");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.Staff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateOnly?>("DriverLicenceExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly?>("FirstAidExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDriverEligible")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFirstAidQualified")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsManualHandlingCompetent")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMedicationCompetent")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOvernightEligible")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly?>("ManualHandlingExpiryDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("MedicationCompetencyExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("Mobile")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Region");

                    b.HasIndex("Role");

                    b.HasIndex("TenantId");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.StaffAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("AssignmentEnd")
                        .HasColumnType("date");

                    b.Property<string>("AssignmentRole")
                        .HasColumnType("text");

                    b.Property<DateOnly>("AssignmentStart")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("HasConflict")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDriver")
                        .HasColumnType("boolean");

                    b.Property<string>("ShiftNotes")
                        .HasColumnType("text");

                    b.Property<int>("SleepoverType")
                        .HasColumnType("integer");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TripInstanceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("TripInstanceId");

                    b.HasIndex("StaffId", "AssignmentStart", "AssignmentEnd");

                    b.ToTable("StaffAssignments");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.StaffAvailability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AvailabilityType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("RecurrenceNotes")
                        .HasColumnType("text");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("AvailabilityType");

                    b.HasIndex("StaffId", "StartDateTime", "EndDateTime");

                    b.ToTable("StaffAvailabilities");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.SupportActivityGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("GroupCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("SupportCategory")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GroupCode")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.ToTable("SupportActivityGroups");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.SupportCatalogueItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActivityGroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("CatalogueVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("DayType")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsIntensive")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("PriceLimit_ACT")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("PriceLimit_NSW")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("PriceLimit_NT")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("PriceLimit_QLD")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("PriceLimit_Remote")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("PriceLimit_SA")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("PriceLimit_TAS")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("PriceLimit_VIC")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("PriceLimit_VeryRemote")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("PriceLimit_WA")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("ActivityGroupId");

                    b.HasIndex("DayType");

                    b.HasIndex("IsActive");

                    b.HasIndex("ItemNumber", "CatalogueVersion");

                    b.ToTable("SupportCatalogueItems");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.SupportProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BehaviourSupportNotes")
                        .HasColumnType("text");

                    b.Property<string>("CommunicationNotes")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("EmergencyConsiderations")
                        .HasColumnType("text");

                    b.Property<string>("ManualHandlingNotes")
                        .HasColumnType("text");

                    b.Property<string>("MedicationHealthSummary")
                        .HasColumnType("text");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid");

                    b.Property<string>("RestrictivePracticeDetails")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("ReviewDate")
                        .HasColumnType("date");

                    b.Property<string>("TravelSpecificNotes")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId")
                        .IsUnique();

                    b.ToTable("SupportProfiles");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("EmailDomain")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmailDomain")
                        .IsUnique();

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.TripClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AuthorisedByStaffId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClaimReference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SubmittedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotalApprovedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("TripInstanceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AuthorisedByStaffId");

                    b.HasIndex("ClaimReference")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("TripInstanceId");

                    b.ToTable("TripClaims");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.TripDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("DayNotes")
                        .HasColumnType("text");

                    b.Property<int>("DayNumber")
                        .HasColumnType("integer");

                    b.Property<string>("DayTitle")
                        .HasColumnType("text");

                    b.Property<bool>("IsPublicHoliday")
                        .HasColumnType("boolean");

                    b.Property<decimal>("OvernightHours")
                        .HasColumnType("numeric");

                    b.Property<int>("OvernightType")
                        .HasColumnType("integer");

                    b.Property<Guid>("TripInstanceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("TripInstanceId", "DayNumber")
                        .IsUnique();

                    b.ToTable("TripDays");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.TripDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateOnly?>("DocumentDate")
                        .HasColumnType("date");

                    b.Property<int>("DocumentType")
                        .HasColumnType("integer");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid?>("ParticipantBookingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TripInstanceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("DocumentType");

                    b.HasIndex("ParticipantBookingId");

                    b.HasIndex("TripInstanceId");

                    b.ToTable("TripDocuments");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.TripInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ActiveHoursPerDay")
                        .HasColumnType("numeric");

                    b.Property<DateOnly?>("BookingCutoffDate")
                        .HasColumnType("date");

                    b.Property<decimal>("CalculatedStaffRequired")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("DefaultActivityGroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("Destination")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("DurationDays")
                        .HasColumnType("integer");

                    b.Property<Guid?>("EventTemplateId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LeadCoordinatorId")
                        .HasColumnType("uuid");

                    b.Property<int?>("MaxParticipants")
                        .HasColumnType("integer");

                    b.Property<int?>("MinParticipants")
                        .HasColumnType("integer");

                    b.Property<int?>("MinStaffRequired")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("RequiredBedrooms")
                        .HasColumnType("integer");

                    b.Property<int?>("RequiredBeds")
                        .HasColumnType("integer");

                    b.Property<int?>("RequiredWheelchairCapacity")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TripCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TripName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("DefaultActivityGroupId");

                    b.HasIndex("EventTemplateId");

                    b.HasIndex("LeadCoordinatorId");

                    b.HasIndex("Region");

                    b.HasIndex("StartDate");

                    b.HasIndex("Status");

                    b.HasIndex("TenantId");

                    b.HasIndex("TripCode")
                        .IsUnique()
                        .HasFilter("\"TripCode\" IS NOT NULL");

                    b.ToTable("TripInstances");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid?>("StaffId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.HasIndex("StaffId");

                    b.HasIndex("TenantId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DriverRequirements")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsInternal")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("RampHoistDetails")
                        .HasColumnType("text");

                    b.Property<string>("Registration")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateOnly?>("RegistrationDueDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ServiceDueDate")
                        .HasColumnType("date");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("VehicleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("VehicleType")
                        .HasColumnType("integer");

                    b.Property<int>("WheelchairPositions")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("TenantId");

                    b.HasIndex("VehicleType");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.VehicleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("ConfirmedDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("DriverStaffId")
                        .HasColumnType("uuid");

                    b.Property<bool>("HasOverlapConflict")
                        .HasColumnType("boolean");

                    b.Property<string>("PickupTravelNotes")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("RequestedDate")
                        .HasColumnType("date");

                    b.Property<int?>("SeatRequirement")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TripInstanceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid");

                    b.Property<int?>("WheelchairPositionRequirement")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DriverStaffId");

                    b.HasIndex("Status");

                    b.HasIndex("TripInstanceId");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleAssignments");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.AccommodationProperty", b =>
                {
                    b.HasOne("TripCore.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.AccommodationReservation", b =>
                {
                    b.HasOne("TripCore.Domain.Entities.AccommodationProperty", "AccommodationProperty")
                        .WithMany("Reservations")
                        .HasForeignKey("AccommodationPropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TripCore.Domain.Entities.TripInstance", "TripInstance")
                        .WithMany("AccommodationReservations")
                        .HasForeignKey("TripInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccommodationProperty");

                    b.Navigation("TripInstance");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.Activity", b =>
                {
                    b.HasOne("TripCore.Domain.Entities.EventTemplate", "EventTemplate")
                        .WithMany("Activities")
                        .HasForeignKey("EventTemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("EventTemplate");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.AppSettings", b =>
                {
                    b.HasOne("TripCore.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.BookingTask", b =>
                {
                    b.HasOne("TripCore.Domain.Entities.AccommodationReservation", "AccommodationReservation")
                        .WithMany("Tasks")
                        .HasForeignKey("AccommodationReservationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TripCore.Domain.Entities.Staff", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TripCore.Domain.Entities.ParticipantBooking", "ParticipantBooking")
                        .WithMany("Tasks")
                        .HasForeignKey("ParticipantBookingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TripCore.Domain.Entities.StaffAssignment", "StaffAssignment")
                        .WithMany("Tasks")
                        .HasForeignKey("StaffAssignmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TripCore.Domain.Entities.TripInstance", "TripInstance")
                        .WithMany("Tasks")
                        .HasForeignKey("TripInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TripCore.Domain.Entities.VehicleAssignment", "VehicleAssignment")
                        .WithMany("Tasks")
                        .HasForeignKey("VehicleAssignmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AccommodationReservation");

                    b.Navigation("Owner");

                    b.Navigation("ParticipantBooking");

                    b.Navigation("StaffAssignment");

                    b.Navigation("TripInstance");

                    b.Navigation("VehicleAssignment");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.ClaimLineItem", b =>
                {
                    b.HasOne("TripCore.Domain.Entities.ParticipantBooking", "ParticipantBooking")
                        .WithMany()
                        .HasForeignKey("ParticipantBookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TripCore.Domain.Entities.TripClaim", "TripClaim")
                        .WithMany("LineItems")
                        .HasForeignKey("TripClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParticipantBooking");

                    b.Navigation("TripClaim");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.EventTemplate", b =>
                {
                    b.HasOne("TripCore.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.IncidentReport", b =>
                {
                    b.HasOne("TripCore.Domain.Entities.Participant", "InvolvedParticipant")
                        .WithMany()
                        .HasForeignKey("InvolvedParticipantId");

                    b.HasOne("TripCore.Domain.Entities.Staff", "InvolvedStaff")
                        .WithMany()
                        .HasForeignKey("InvolvedStaffId");

                    b.HasOne("TripCore.Domain.Entities.ParticipantBooking", "ParticipantBooking")
                        .WithMany()
                        .HasForeignKey("ParticipantBookingId");

                    b.HasOne("TripCore.Domain.Entities.Staff", "ReportedByStaff")
                        .WithMany()
                        .HasForeignKey("ReportedByStaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TripCore.Domain.Entities.Staff", "ReviewedByStaff")
                        .WithMany()
                        .HasForeignKey("ReviewedByStaffId");

                    b.HasOne("TripCore.Domain.Entities.TripInstance", "TripInstance")
                        .WithMany("IncidentReports")
                        .HasForeignKey("TripInstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InvolvedParticipant");

                    b.Navigation("InvolvedStaff");

                    b.Navigation("ParticipantBooking");

                    b.Navigation("ReportedByStaff");

                    b.Navigation("ReviewedByStaff");

                    b.Navigation("TripInstance");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.Participant", b =>
                {
                    b.HasOne("TripCore.Domain.Entities.Contact", "PlanManagerContact")
                        .WithMany()
                        .HasForeignKey("PlanManagerContactId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TripCore.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanManagerContact");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.ParticipantBooking", b =>
                {
                    b.HasOne("TripCore.Domain.Entities.Participant", "Participant")
                        .WithMany("Bookings")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TripCore.Domain.Entities.TripInstance", "TripInstance")
                        .WithMany("Bookings")
                        .HasForeignKey("TripInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participant");

                    b.Navigation("TripInstance");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.ParticipantContact", b =>
                {
                    b.HasOne("TripCore.Domain.Entities.Contact", "Contact")
                        .WithMany("ParticipantContacts")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TripCore.Domain.Entities.Participant", "Participant")
                        .WithMany("ParticipantContacts")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.ScheduledActivity", b =>
                {
                    b.HasOne("TripCore.Domain.Entities.Activity", "Activity")
                        .WithMany("ScheduledActivities")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TripCore.Domain.Entities.TripDay", "TripDay")
                        .WithMany("ScheduledActivities")
                        .HasForeignKey("TripDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("TripDay");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.Staff", b =>
                {
                    b.HasOne("TripCore.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.StaffAssignment", b =>
                {
                    b.HasOne("TripCore.Domain.Entities.Staff", "Staff")
                        .WithMany("Assignments")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TripCore.Domain.Entities.TripInstance", "TripInstance")
                        .WithMany("StaffAssignments")
                        .HasForeignKey("TripInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");

                    b.Navigation("TripInstance");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.StaffAvailability", b =>
                {
                    b.HasOne("TripCore.Domain.Entities.Staff", "Staff")
                        .WithMany("AvailabilityRecords")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.SupportCatalogueItem", b =>
                {
                    b.HasOne("TripCore.Domain.Entities.SupportActivityGroup", "ActivityGroup")
                        .WithMany("Items")
                        .HasForeignKey("ActivityGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActivityGroup");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.SupportProfile", b =>
                {
                    b.HasOne("TripCore.Domain.Entities.Participant", "Participant")
                        .WithOne("SupportProfile")
                        .HasForeignKey("TripCore.Domain.Entities.SupportProfile", "ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.TripClaim", b =>
                {
                    b.HasOne("TripCore.Domain.Entities.Staff", "AuthorisedByStaff")
                        .WithMany()
                        .HasForeignKey("AuthorisedByStaffId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TripCore.Domain.Entities.TripInstance", "TripInstance")
                        .WithMany("TripClaims")
                        .HasForeignKey("TripInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthorisedByStaff");

                    b.Navigation("TripInstance");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.TripDay", b =>
                {
                    b.HasOne("TripCore.Domain.Entities.TripInstance", "TripInstance")
                        .WithMany("TripDays")
                        .HasForeignKey("TripInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TripInstance");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.TripDocument", b =>
                {
                    b.HasOne("TripCore.Domain.Entities.ParticipantBooking", "ParticipantBooking")
                        .WithMany("Documents")
                        .HasForeignKey("ParticipantBookingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TripCore.Domain.Entities.TripInstance", "TripInstance")
                        .WithMany("Documents")
                        .HasForeignKey("TripInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParticipantBooking");

                    b.Navigation("TripInstance");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.TripInstance", b =>
                {
                    b.HasOne("TripCore.Domain.Entities.SupportActivityGroup", "DefaultActivityGroup")
                        .WithMany()
                        .HasForeignKey("DefaultActivityGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TripCore.Domain.Entities.EventTemplate", "EventTemplate")
                        .WithMany("TripInstances")
                        .HasForeignKey("EventTemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TripCore.Domain.Entities.Staff", "LeadCoordinator")
                        .WithMany()
                        .HasForeignKey("LeadCoordinatorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TripCore.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DefaultActivityGroup");

                    b.Navigation("EventTemplate");

                    b.Navigation("LeadCoordinator");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.User", b =>
                {
                    b.HasOne("TripCore.Domain.Entities.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TripCore.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.Vehicle", b =>
                {
                    b.HasOne("TripCore.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.VehicleAssignment", b =>
                {
                    b.HasOne("TripCore.Domain.Entities.Staff", "DriverStaff")
                        .WithMany()
                        .HasForeignKey("DriverStaffId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TripCore.Domain.Entities.TripInstance", "TripInstance")
                        .WithMany("VehicleAssignments")
                        .HasForeignKey("TripInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TripCore.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("Assignments")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DriverStaff");

                    b.Navigation("TripInstance");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.AccommodationProperty", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.AccommodationReservation", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.Activity", b =>
                {
                    b.Navigation("ScheduledActivities");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.Contact", b =>
                {
                    b.Navigation("ParticipantContacts");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.EventTemplate", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("TripInstances");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.Participant", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("ParticipantContacts");

                    b.Navigation("SupportProfile");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.ParticipantBooking", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.Staff", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("AvailabilityRecords");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.StaffAssignment", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.SupportActivityGroup", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.TripClaim", b =>
                {
                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.TripDay", b =>
                {
                    b.Navigation("ScheduledActivities");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.TripInstance", b =>
                {
                    b.Navigation("AccommodationReservations");

                    b.Navigation("Bookings");

                    b.Navigation("Documents");

                    b.Navigation("IncidentReports");

                    b.Navigation("StaffAssignments");

                    b.Navigation("Tasks");

                    b.Navigation("TripClaims");

                    b.Navigation("TripDays");

                    b.Navigation("VehicleAssignments");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.Vehicle", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("TripCore.Domain.Entities.VehicleAssignment", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
